language: python
python:
  - "2.7"
cache: apt
addons:
  sources:
  - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
  apt:
    packages:
    - qgis
    - python-qgis
script: nosetests -w GeoDanmarkChecker/test/regression/

