language: python
python:
  - "2.7"
cache: apt
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
    - qgis
    - python-qgis
script: nosetests -w GeoDanmarkChecker/test/regression/

