language: python
python:
  - "2.7_with_system_site_packages"
cache: apt
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    - sourceline: 'deb http://qgis.org/debian precise main'
      key_url: 'http://qgis.org/downloads/qgis-2016.gpg.key'
    packages:
    - qgis
    - python-qgis
script: nosetests -w GeoDanmarkChecker/test/regression/

