language: python
python:
  - "2.7_with_system_site_packages"
cache: apt
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    - sourceline: 'deb http://qgis.org/ubuntugis-ltr precise main'
      key_url: 'http://qgis.org/downloads/qgis-2016.gpg.key'
    packages:
    - qgis
    - python-qgis
script: nosetests -w GeoDanmarkChecker/test/regression/
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/380674ca32c086e9647e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always